version: '3'
services:
  client:
    build: 
      context: .
      dockerfile: ./Dockerfile 
    restart: on-failure
    volumes:
      - .:/app
      # - /app/node_modules 
    networks:
      - blog-cms-fe

networks:
  blog-cms-fe:
# volumes:
#   /app/node_modules:
